### PR TITLE
chore: merge v3.6.0

### PR DESCRIPTION
**Pull request by krispraws**
## Description
- Pull in v3.6.0 from upstream to get the syscall latency breakdown feature.
- Relax clippy rules `unwrap_used` and `expect_used` to get over build errors.
- We need to update [the config file ](https://github.com/momentohq/typescript-kitchensink/blob/7425d70021edb4d027e7a7be816045f920091ced/cdk-and-cdktf/src/momento-monitoring-bootstrap/otel-collector.ts#L121) to add new required sections from [updated config](https://github.com/iopsystems/rezolus/blob/main/config.toml). Otherwise rezolus fails to start up.
```
Oct 30 22:46:50 ip-10-0-5-76 systemd: Started Rezolus is a systems performance telemetry agent.
Oct 30 22:46:50 ip-10-0-5-76 rezolus: failed to parse config file: TOML parse error at line 1, column 1
Oct 30 22:46:50 ip-10-0-5-76 rezolus: |
Oct 30 22:46:50 ip-10-0-5-76 rezolus: 1 | [general]
Oct 30 22:46:50 ip-10-0-5-76 systemd: rezolus.service: main process exited, code=exited, status=1/FAILURE
Oct 30 22:46:50 ip-10-0-5-76 rezolus: | ^
Oct 30 22:46:50 ip-10-0-5-76 rezolus: missing field `prometheus`
Oct 30 22:46:50 ip-10-0-5-76 systemd: Unit rezolus.service entered failed state.
Oct 30 22:46:50 ip-10-0-5-76 systemd: rezolus.service failed.
```

## Changes pulled in from upstream
- begin next development iteration (#56)
- update dependencies (#59)
- Add support for cross compiling and arm64 debian package (#60)
- prepare for release v3.3.3 (#61)
- begin next development iteration (#62)
- chore: cleanup (#64)
- Add github actions job to upload deb packages as release artifacts (#65)
- use percentiles api to reduce cost of calculating percentiles (#66)
- Update warp to fix DoS in tungstenite (RUSTSEC-2023-0065)
- Extract the hwinfo sampler into a separate systeminfo crate (#68)
- Clean up the `systeminfo` crate (#70)
- update changelog and prepare for release 3.4.0 (#71)
- begin next development iteration (#72)
- Fix packaging release workflow (#73)
- update metriken to replace heatmaps (#67)
- update changelog and prepare for release 3.5.0 (#74)
- begin next development iteration (#75)
- add dependabot config (#76)
- fix: address clippy lints (#77)
- fix: dependabot config (#78)
- feat: allow enabling/disabling of samplers (#63)
- chore: change dependabot versioning strategy (#81)
- remove dependency on `clocksource` (#80)
- chore(deps): bump regex-automata from 0.3.6 to 0.3.9 (#83)
- chore(deps): bump regex-syntax from 0.7.4 to 0.7.5 (#82)
- chore(deps): bump tracing-core from 0.1.31 to 0.1.32 (#84)
- chore(deps): bump the cargo-dependencies group with 38 updates (#85)
- chore: remove clocksource from Cargo.toml
- feat: add TCP connection state sampler (#87)
- chore(deps): bump the cargo-dependencies group with 13 updates (#88)
- adjust tcp connection state sampler interval in example config (#89)
- feat: add sampler for Rezolus itself (#90)
- fix: histogram mmap length check (#92)
- feat(sampler): change CPU features from a string to an array (#91)
- feat: prometheus histograms (#94)
- feat: track latencies for syscall famlies (#93)
- update changelog and prepare for release v3.6.0 (#95)

## Changes from our fork
- [chore: relax clippy rules](https://github.com/momentohq/rezolus/commit/e01542ef11e1f2dc0af0887e2e823bec54a80c18)

### CODE REVIEW

**Review by mjindalmotiv8 — APPROVED** [review]
Let’s make sure to block in cacheservice so that we can evaluate with daily load test - I do not remember if this is auto picked up

**Comment by krispraws** [comment]
> Let’s make sure to block in cacheservice so that we can evaluate with daily load test - I do not remember if this is auto picked up

I am testing this in my dev cell first - will add a block in cacheservice when i merge this.

**Review by honeyAcorn — APPROVED** [review]
Just wanna give a friendly reminder about the next steps here:

https://www.notion.so/momentohq/Rezolus-c35a8356c4bf4fc8940a6899bd09ea75?pvs=4#87e73520687b42c9a3e3c4f1c9387937

Please feel free to update this notion doc too.

Otherwise can you just make sure it runs on your dev-cell and lightstep still working? Thanks!

**Comment by krispraws** [comment]
> Just wanna give a friendly reminder about the next steps here:
> 
> https://www.notion.so/momentohq/Rezolus-c35a8356c4bf4fc8940a6899bd09ea75?pvs=4#87e73520687b42c9a3e3c4f1c9387937
> 
> Please feel free to update this notion doc too.
> 
> Otherwise can you just make sure it runs on your dev-cell and lightstep still working? Thanks!

I tested in my dev cell and I had to update the config to get it run like I mentioned in the PR description. I am going to hold off on merging this PR till we figure out how to version rezolus.

**Pull request closed without merging**
